import { Platform, StyleSheet } from 'react-native';

import { ColorTheme, FONT, SIZES } from '@/theme';
import { deviceWidth, px } from '@/utils';

export const styles = StyleSheet.create({
  container: {
    height: px(150),
    backgroundColor: '#FDFFEC',
    shadowOffset: {
      width: 1,
      height: 1,
    },
    shadowOpacity: Platform.OS === 'android' ? 1 : 0.3,
    shadowRadius: 5,
    shadowColor: 'gray',
    elevation: 10,
    borderRadius: 9,
    alignSelf: 'center',
    width: deviceWidth / 1.2,
    borderWidth: 0.3,
    borderColor: ColorTheme.nearLukGray2,
  },
  flatListStyle: { paddingLeft: px(20), paddingRight: px(100) },
  headText: { fontSize: SIZES.medium18, color: ColorTheme.black },
  headView: {
    width: deviceWidth,
    // height: px(20),
    paddingLeft: px(20),
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingBottom: px(5),
  },
  bhkView: {
    marginVertical: px(20),
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
  },
  bhkText: {
    fontSize: SIZES.medium,
    fontWeight: '500',
  },
  priceText1: {
    fontSize: SIZES.medium,
    fontWeight: '500',
  },
  moreText: {
    fontSize: SIZES.small,
    color: ColorTheme.primary,
    textDecorationLine: 'underline',
    padding: px(5),
    paddingRight: px(10),
  },
  btnView: {
    position: 'absolute',
    bottom: px(10),
    right: px(10),
    width: px(80),
    height: px(25),
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 0.3,
    borderRadius: px(10),
    backgroundColor: ColorTheme.primary,
  },
  btnText: { fontSize: SIZES.small, fontWeight: '500' },
  imgContainer: {
    flex: 1,
    flexDirection: 'column',

    padding: 10,
  },
  propLocality: {
    marginVertical: 1,
    color: 'black',
    marginTop: 5,

    fontFamily: FONT.PoppinsRegular,
    fontSize: SIZES.xSmall,
    opacity: 0.5,
    fontWeight: '400',
  },
  typeText: {
    marginVertical: 1,
    color: 'black',
    fontFamily: FONT.PoppinsRegular,
    fontSize: SIZES.xSmall,
    opacity: 0.5,
    fontWeight: '400',
  },
  propPrice: {
    fontSize: SIZES.medium15,
    fontFamily: FONT.PoppinsMedium,
    fontWeight: '600',
    color: 'black',
  },
  rowContainer: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  imageContainer: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',

    // gap: 1,
  },
  imageStyle: {
    width: '100%',
    height: '100%',
    borderTopLeftRadius: 8,
    borderBottomLeftRadius: 8,
  },
  absoluteView: {
    position: 'absolute',
    top: 0,
    width: 100,
    height: 50,
  },
  imageBGContainer: {
    width: '100%',
    height: '100%',
  },
  verifiedView: {
    position: 'absolute',
    top: 15,
    alignSelf: 'center',
  },
  verifiedText: {
    fontSize: SIZES.small,
    color: 'black',
    fontFamily: FONT.PoppinsMedium,
    fontWeight: '500',
  },
  priceContainer: {
    position: 'absolute',
    bottom: 10,
    right: 20,
  },
  priceText: {
    fontSize: SIZES.medium,
    color: 'white',
    fontFamily: FONT.PoppinsMedium,
    fontWeight: 'bold',
  },
  reraView: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    backgroundColor: 'black',
    paddingHorizontal: px(10),
    borderRadius: 8,
    paddingVertical: px(4),
  },
  reraText: {
    fontSize: SIZES.medium15,
    color: 'white',
    fontFamily: FONT.PoppinsMedium,
    fontWeight: '500',
  },
  rowView: {
    flexDirection: 'row',

    gap: 5,
  },
  flexView: {
    flex: 3.5,
  },
  propertyText: {
    fontSize: SIZES.small,
    fontFamily: FONT.PoppinsMedium,
    fontWeight: '700',
    color: 'black',
  },
  typeView: {
    padding: 3,
    borderWidth: 0.5,
    borderColor: 'gray',
    borderRadius: 2,
    marginLeft: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  facingView: {
    borderWidth: 1,
    borderColor: 'gray',
    padding: 5,
    marginTop: 20,
    borderRadius: 4,
  },
  colummView: {
    flexDirection: 'column',
  },
  lineView: {
    backgroundColor: 'black',
    height: 35,
    width: 1,
    marginLeft: 5,
  },
  endView: {
    flexDirection: 'column',
    marginLeft: 5,
  },
  facingText: {
    fontSize: SIZES.small13,
    color: '#8F8F8F',
    fontWeight: '500',
  },
  subType: {
    padding: 3,
    borderWidth: 0.5,
    borderColor: 'gray',
    borderRadius: 4,
    marginTop: 10,
  },
  sqView: {
    alignContent: 'center',
    alignItems: 'center',
    marginTop: 10,
  },
  durationText: {
    width: 20,
    height: 10,
    marginTop: 7,
    color: 'black',
  },
  lastView: {
    padding: 4,
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginTop: 10,
  },
  bottomLineView: {
    position: 'absolute',
    bottom: 0,
    height: px(40),
    width: px(160),
    backgroundColor: 'rgba(0,0,0,0.5)',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
  },
  bottomLineText: {
    fontSize: SIZES.medium15,
    fontWeight: '500',
    color: ColorTheme.primary,
  },
  bannerContainer: {
    width: deviceWidth,
    alignItems: 'center',
    justifyContent: 'center',
  },
  insideContainer: {
    height: px(150),
    position: 'relative',
  },
  imageContainer1: {
    width: deviceWidth / 1.09,
    height: px(150),
    borderRadius: 10,
    padding: px(5),
    //   backgroundColor: "aqua",
  },
  wrapper: {
    marginTop: px(30),
    height: px(150),
  },
  slide1: {
    // flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'white',
    height: px(150),
  },
  slide2: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#97CAE5',
  },
  slide3: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#92BBD9',
  },
  text: {
    color: '#fff',
    fontSize: px(30),
    fontWeight: 'bold',
  },
  pagination: {
    alignSelf: 'flex-start',
    // backgroundColor: 'black',
  },
  dotstyle: {
    width: px(5),
    height: px(5),
    borderRadius: px(5),
    color: 'transparent',
  },
  activeDotStyle: {
    width: px(9),
    height: px(9),
    borderRadius: px(9),
    color: 'transparent',
  },
});
