import { Platform, StyleSheet } from 'react-native';

import { ColorTheme, FONT, SIZES } from '@/theme';
import { deviceWidth } from '@/utils';

export const styles = StyleSheet.create({
  topMain: {
    width: deviceWidth / 1.09,
    alignSelf: 'center',
  },
  username: {
    fontFamily: FONT.PoppinsBold,
    fontSize: SIZES.large,
    textTransform: 'capitalize',
    fontWeight: '600',
    color: 'black',
  },
  likesMain: {
    flexDirection: 'row',
    gap: 10,
  },
  likesText: {
    fontFamily: FONT.PoppinsRegular,
    fontSize: SIZES.small13,
    fontWeight: '400',
    color: 'black',
  },
  followText: {
    fontFamily: FONT.PoppinsRegular,
    fontSize: 14,
    color: 'black',
  },
  rating: {
    flexDirection: 'row',
    gap: 5,
    marginTop: 5,
    alignItems: 'center',
  },
  mainBtnGroup: {
    gap: 5,
    flexDirection: 'row',
  },
  btnTextStyle: {
    color: 'black',
    fontSize: SIZES.small13,
    fontFamily: FONT.PoppinsRegular,
  },
  sectionContainer: { width: deviceWidth, alignItems: 'center' },
  sectionDetailPart: {
    flexDirection: 'column',
    alignContent: 'center',
    justifyContent: 'flex-start',
    width: deviceWidth / 1.09,
  },
  detailText: { fontSize: SIZES.small, fontWeight: '400', color: 'black' },
  detailSection: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    paddingVertical: 5,
  },
  detaillogos: { width: 13, height: 13 },
  bottombtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 20,
    width: deviceWidth,
  },
  editBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    width: deviceWidth / 1.09,
  },
  buttenstyle: {
    flex: 1,
    backgroundColor: ColorTheme.nearLukGray4,
    minHeight: 39,
  },
  textBtnstyle: {
    color: 'black',
    fontSize: SIZES.medium15,
    fontFamily: FONT.PoppinsMedium,
  },
  customBtn: {
    flex: 5,
    backgroundColor: ColorTheme.nearLukGray4,
    minHeight: 39,
  },
  customBtnText: {
    color: 'black',
    fontSize: SIZES.small13,
    fontFamily: FONT.PoppinsRegular,
    fontWeight: '500',
    lineHeight: 22,
  },
  topTabContainerStyle: {
    flexDirection: 'row',
    gap: 10,
    alignItems: 'center',
    // width: deviceWidth,
    paddingVertical: 6,
    // marginTop: 10,
    marginLeft: 10,
  },
  renderImg: { height: 24, width: 24, marginRight: 5 },
  backgroundImg: {
    height: 250,
    width: deviceWidth,
    backgroundColor: ColorTheme.nearLukGray3,
    borderBottomLeftRadius: 15,
    borderBottomRightRadius: 15,
    overflow: 'hidden',
    // opacity: 0.6,
  },
  userCamera: {
    height: 37,
    width: 37,
    borderRadius: 30,
    borderWidth: 2,
    borderColor: 'white',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    bottom: 10,
    right: 10,
    backgroundColor: ColorTheme.nearLukGray4,
  },
  cameraPic: { height: 37, width: 37 },
  userProfile: {
    backgroundColor: ColorTheme.nearLukGray3,
    // padding: 5,
    borderRadius: 100,
    position: 'absolute',
    left: 20,
    bottom: -45,
    zIndex: 999,
    borderWidth: 4,
    borderColor: 'white',
  },
  profileCamera: {
    height: 37,
    width: 37,
    borderRadius: 30,
    borderWidth: 2,
    borderColor: 'white',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    bottom: 0,
    right: 0,
    zIndex: 2,
    backgroundColor: ColorTheme.nearLukGray4,
  },
  bioContainer: {
    marginTop: 5,
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'flex-end',
    flex: 1,
  },
  bioTextStyle: {
    lineHeight: 16,
    fontSize: SIZES.small11,
    fontWeight: '400',
    color: 'black',
    flex: 1,
  },
  moreBtn: {
    lineHeight: 16,
    fontSize: SIZES.small,
    color: 'blue',
    fontWeight: '400',
    flex: 1,
  },
  customMore: {
    flex: 1,
    backgroundColor: ColorTheme.nearLukGray4,
    paddingHorizontal: 5,
    minHeight: 39,
  },
  customMoreText: {
    color: 'black',
    fontSize: 25,
    fontFamily: FONT.PoppinsMedium,
    textAlign: 'center',
    lineHeight: 20,
  },
  chips: {
    fontSize: SIZES.small13,
    fontFamily: FONT.PoppinsRegular,
    color: 'black',
  },
  subheading: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    position: 'relative',
    bottom: 10,
  },
  subText: {
    fontSize: SIZES.small,
    color: 'black',
    fontWeight: '400',
  },
  whatsMind: {
    width: deviceWidth / 1.09,
    height: 60,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    marginBottom: 10,
  },
  whatsMindMain: {
    alignItems: 'center',
    justifyContent: 'flex-start',
    flexDirection: 'row',
  },
  imgStyle: { height: 45, width: 45, borderRadius: 45 },
  mindText: {
    paddingLeft: 10,
    fontSize: SIZES.small,
    fontWeight: '400',
    lineHeight: 18,
    color: 'black',
  },
  rightImg: { height: 25, width: 25, borderRadius: 5 },
  textTab: {
    color: 'black',
    fontSize: SIZES.medium15,
    fontWeight: '500',
    lineHeight: 22,
  },
  horizontalScroll: {
    height: 50,
    marginVertical: 5,
    width: deviceWidth / 1.09,
    backgroundColor: 'white',
  },
  userIcon: {
    width: 100,
    height: 100,
    borderRadius: 100,
    justifyContent: 'center',
    alignItems: 'center',
    // borderWidth: 1,
    backgroundColor: ColorTheme.primary,
  },
  userLetter: {
    textTransform: 'capitalize',
    fontSize: SIZES.xxLarge,
    fontFamily: FONT.PoppinsBold,
    lineHeight: 35,
    color: 'white',
  },
  userIcon1: {
    height: 45,
    width: 45,
    borderRadius: 45,
    justifyContent: 'center',
    alignItems: 'center',
    // borderWidth: 1,
    backgroundColor: ColorTheme.primary,
  },
  userLetter1: {
    textTransform: 'capitalize',
    fontSize: SIZES.large,
    fontFamily: FONT.PoppinsBold,
    lineHeight: 35,
    color: 'white',
  },
  keyboardView: { flex: 1, paddingBottom: 25 },
  topScroll: { paddingBottom: 50 },
  topScrollStyle: {
    backgroundColor: 'white',
  },
  comingSoon: {
    flexDirection: 'row',
    width: deviceWidth,
    height: 200,
    alignItems: 'center',
    justifyContent: 'center',
  },
  comingText: {
    fontSize: SIZES.medium15,
    fontFamily: FONT.PoppinsMedium,
    color: 'black',
  },
  userTabView: {
    flexDirection: 'row',
    gap: 10,
    alignItems: 'center',
    width: deviceWidth,
    paddingVertical: 6,
  },
  topProfileView: {
    marginBottom: 30,
  },
  profileImg: {
    width: 100,
    height: 100,
    borderRadius: 100,
  },
  userNameView: {
    marginTop: 15,
    flexDirection:'row',
    alignItems:'center'
  },
  divider: { marginTop: 5 },
  headerView: { width: deviceWidth / 1.09 },
  chipView: { backgroundColor: '#E2E2E2', height: 52 },
  contentContainer: { paddingLeft: 20, paddingRight: 100 },
  chipStyle: {
    shadowOpacity: Platform.OS === 'android' ? 1 : 0.3,
    shadowRadius: 3,
    // shadowColor: "gray",
    // padding: 10,
    borderRadius: 100,
    paddingHorizontal: 30,
    elevation: 0, // Android only (elevation creates shadow)
  },
  buttonsView: {
    alignSelf: 'center',
    gap: 15,
    marginTop: 10,
  },
  hideBtn: {
    width: deviceWidth / 1.09,
  },
  dividerView: {
    marginTop: 12,
    width: deviceWidth,
    borderBottomWidth: 8,
    borderBottomColor: ColorTheme.nearLukGray4,
  },
  headingTextStyle: { fontSize: SIZES.medium15, color: 'black' },
  propertyChips: {
    justifyContent: 'center',
    shadowOpacity: Platform.OS === 'android' ? 1 : 0.3,
    shadowRadius: 3,
    // shadowColor: "gray",
    // padding: 10,
    borderRadius: 100,
    paddingHorizontal: 30,
    elevation: 0, // Android only (elevation creates shadow)
  },
});
