import { Platform, StyleSheet } from 'react-native';

import { ColorTheme, FONT, SIZES } from '@/theme';
import { deviceHeight, deviceWidth, px } from '@/utils';

export const styles = StyleSheet.create({
  topMain: {
    width: deviceWidth / 1.09,
    alignSelf: 'center',
    justifyContent:'center',
  },
  username: {
    fontFamily: FONT.PoppinsBold,
    fontSize: SIZES.large,
    textTransform: 'capitalize',
    fontWeight: '600',
    alignSelf:'center',
    color: 'black',
  },
  likesMain: {
    flexDirection: 'row',
    justifyContent:'center',
    gap: 5,
  },
  likesText: {
    fontFamily: FONT.PoppinsRegular,
    fontSize: SIZES.small13,
    fontWeight: '400',
    color: 'black',
  },
  followText: {
    fontFamily: FONT.PoppinsRegular,
    fontSize: 14,
    color: 'black',
  },
  rating: {
    flexDirection: 'row',
    gap: 5,
    marginTop: 5,
    alignItems: 'center',
  },
  mainBtnGroup: {
    gap: 5,
    flexDirection: 'row',
  },
  btnTextStyle: {
    color: 'black',
    fontSize: SIZES.small13,
    fontFamily: FONT.PoppinsRegular,
  },
  sectionContainer: { width: deviceWidth, alignItems: 'center'},
  sectionDetailPart: {
    flexDirection: 'column',
    alignContent: 'center',
    justifyContent: 'flex-start',
    width: deviceWidth / 1.09,
  },
  detailText: { fontSize: SIZES.small, fontWeight: '400', color: 'black' },
  detailSection: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    paddingVertical: 5,
  },
  detaillogos: { width: 13, height: 13 },
  bottombtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 20,
    width: deviceWidth,
  },
  editBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    width: deviceWidth / 1.09,
  },
  buttenstyle: {
    flex: 1,
    backgroundColor: ColorTheme.nearLukGray4,
    minHeight: 39,
  },
  textBtnstyle: {
    color: 'black',
    fontSize: SIZES.medium15,
    fontFamily: FONT.PoppinsMedium,
  },
  customBtn: {
    flex: 5,
    backgroundColor: ColorTheme.nearLukGray4,
    minHeight: 39,
  },
  customBtnText: {
    color: 'black',
    fontSize: SIZES.small13,
    fontFamily: FONT.PoppinsRegular,
    fontWeight: '500',
    lineHeight: 22,
  },
  topTabContainerStyle: {
    flexDirection: 'row',
    gap: 10,
    alignItems: 'center',
    // width: deviceWidth,
    paddingVertical: 6,
    // marginTop: 10,
    marginLeft: 10,
  },
  renderImg: { height: 24, width: 24, marginRight: 5 },
  backgroundImg: {
    height: 250,
    width: deviceWidth,
    backgroundColor: ColorTheme.nearLukGray3,
    borderBottomLeftRadius: 15,
    borderBottomRightRadius: 15,
    overflow: 'hidden',
    // opacity: 0.6,
  },
  userCamera: {
    height: 37,
    width: 37,
    borderRadius: 30,
    borderWidth: 2,
    borderColor: 'white',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    bottom: 10,
    right: 10,
    backgroundColor: ColorTheme.nearLukGray4,
  },
  cameraPic: { height: 37, width: 37 },
  userProfile: {
    backgroundColor: ColorTheme.nearLukGray3,
    // padding: 5,
    borderRadius: 100,
    position: 'absolute',
    left: 20,
    bottom: -45,
    zIndex: 999,
    borderWidth: 4,
    borderColor: 'white',
    justifyContent:'center'
  },
  profileCamera: {
    height: 37,
    width: 37,
    borderRadius: 30,
    borderWidth: 2,
    borderColor: 'white',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    bottom: 0,
    right: 0,
    zIndex: 2,
    backgroundColor: ColorTheme.nearLukGray4,
  },
  bioContainer: {
    marginTop: 5,
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'flex-end',
    flex: 1,
  },
  bioTextStyle: {
    lineHeight: 16,
    fontSize: SIZES.small11,
    fontWeight: '400',
    color: 'black',
    flex: 1,
  },
  moreBtn: {
    lineHeight: 16,
    fontSize: SIZES.small,
    color: 'blue',
    fontWeight: '400',
    flex: 1,
  },
  customMore: {
    flex: 1,
    backgroundColor: ColorTheme.nearLukGray4,
    paddingHorizontal: 5,
    minHeight: 39,
  },
  customMoreText: {
    color: 'black',
    fontSize: 25,
    fontFamily: FONT.PoppinsMedium,
    textAlign: 'center',
    lineHeight: 20,
  },
  chips: {
    fontSize: SIZES.small13,
    fontFamily: FONT.PoppinsRegular,
    color: 'black',
  },
  subheading: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    position: 'relative',
    bottom: 10,
  },
  subText: {
    fontSize: SIZES.small,
    color: 'black',
    fontWeight: '400',
  },
  whatsMind: {
    width: deviceWidth / 1.09,
    height: 60,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    marginBottom: 10,
  },
  whatsMindMain: {
    alignItems: 'center',
    justifyContent: 'flex-start',
    flexDirection: 'row',
  },
  imgStyle: { height: 45, width: 45, borderRadius: 45 },
  mindText: {
    paddingLeft: 10,
    fontSize: SIZES.small,
    fontWeight: '400',
    lineHeight: 18,
    color: 'black',
  },
  rightImg: { height: 25, width: 25, borderRadius: 5 },
  textTab: {
    color: 'black',
    fontSize: SIZES.medium15,
    fontWeight: '500',
    lineHeight: 22,
  },
  horizontalScroll: {
    height: 50,
    marginVertical: 5,
    width: deviceWidth / 1.09,
    backgroundColor: 'white',
  },
  userIcon: {
    width: 100,
    height: 100,
    borderRadius: 100,
    justifyContent: 'center',
    alignItems: 'center',
    // borderWidth: 1,
    backgroundColor: ColorTheme.primary,
  },
  userLetter: {
    textTransform: 'capitalize',
    fontSize: SIZES.xxLarge,
    fontFamily: FONT.PoppinsBold,
    lineHeight: 35,
    color: 'white',
  },
  userIcon1: {
    height: 45,
    width: 45,
    borderRadius: 45,
    justifyContent: 'center',
    alignItems: 'center',
    // borderWidth: 1,
    backgroundColor: ColorTheme.primary,
  },
  userLetter1: {
    textTransform: 'capitalize',
    fontSize: SIZES.large,
    fontFamily: FONT.PoppinsBold,
    lineHeight: 35,
    color: 'white',
  },
  keyboardView: { flex: 1, paddingBottom: 25 },
  topScroll: { paddingBottom: 50 },
  topScrollStyle: {
    backgroundColor: 'white',
  },
  comingSoon: {
    flexDirection: 'row',
    width: deviceWidth,
    height: 200,
    alignItems: 'center',
    justifyContent: 'center',
  },
  comingText: {
    fontSize: SIZES.medium15,
    fontFamily: FONT.PoppinsMedium,
    color: 'black',
  },
  userTabView: {
    flexDirection: 'row',
    gap: 10,
    alignItems: 'center',
    width: deviceWidth,
    paddingVertical: 6,
  },
  topProfileView: {
    marginBottom: 30,
  },
  profileImg: {
    width: 100,
    height: 100,
    borderRadius: 100,
  },
  userNameView: {
    marginTop: 15,
  },
  divider: { marginTop: 5 },
  headerView: { width: deviceWidth / 1.09 },
  chipView: { backgroundColor: '#E2E2E2', height: 52 },
  contentContainer: { paddingLeft: 20, paddingRight: 100 },
  chipStyle: {
    shadowOpacity: Platform.OS === 'android' ? 1 : 0.3,
    shadowRadius: 3,
    // shadowColor: "gray",
    // padding: 10,
    borderRadius: 100,
    paddingHorizontal: 30,
    elevation: 0, // Android only (elevation creates shadow)
  },
  buttonsView: {
    alignSelf: 'center',
    gap: 15,
    marginTop: 10,
  },
  hideBtn: {
    width: deviceWidth / 1.09,
  },
  dividerView: {
    marginTop: 12,
    width: deviceWidth,
    borderBottomWidth: 8,
    borderBottomColor: ColorTheme.nearLukGray4,
  },
  headingTextStyle: { fontSize: SIZES.medium15, color: 'black' },
  propertyChips: {
    justifyContent: 'center',
    shadowOpacity: Platform.OS === 'android' ? 1 : 0.3,
    shadowRadius: 3,
    // shadowColor: "gray",
    // padding: 10,
    borderRadius: 100,
    paddingHorizontal: 30,
    elevation: 0, // Android only (elevation creates shadow)
  },

  amenticeViewStyle: {
    borderColor: ColorTheme.gray,
    borderWidth: 0.5,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: px(10),
    marginBottom: px(10),
    width: px(100),
  },
  amenticeText: {
    fontFamily: FONT.PoppinsRegular,
    fontSize: px(10),
    textAlign: 'center',
    padding: px(5),
    margin: px(5),
  },
  amenticeImage: {
    marginTop: px(15),
  },
  businessNameContainer: { flexDirection: 'row',marginVertical:px(5) },
  followTextStyle: {
    fontFamily: FONT.PoppinsRegular,
    fontSize: px(14),
    fontWeight: 'bold',
    color: ColorTheme.onboardingButton,
    marginHorizontal:px(5),
  },
  ratingStyle: { paddingVertical: 5, alignSelf: 'center', marginLeft: px(40) },
  businessView: { flex: 1 },
  businessBackgroundImage: {
    width: deviceWidth,
    height: deviceHeight / 4,
  },
  containerView: {
    width: deviceWidth / 1.09,
    alignSelf: 'center',
    marginVertical: 10,
    flexDirection: 'column',
    gap: 10,
  },
  businessBackgroundcontainer: {
    width: deviceWidth,
    height: deviceHeight / 4,
    backgroundColor: 'white',
    elevation: 5,
  },

  noDataView: {
    justifyContent: 'center',
    alignItems: 'center',
    height: deviceHeight - px(600),
  },
  noDataText: {
    fontSize: SIZES.medium18,
    color: 'black',
  },

  profileImageStyle: { width: px(80), height: px(80), borderRadius: px(40), backgroundColor: ColorTheme.black },
  cameraContainer: { marginLeft: px(40) },
  cameraImageStyle: {
    width: px(20),
    height: px(20),
    borderRadius: px(10),
    backgroundColor: ColorTheme.black,
    marginLeft: px(60),
    marginTop: px(-25),
  },
  businessNameStyle: { position: 'absolute', alignSelf: 'center' },
  businessDescriptionStyle: {
    fontFamily: FONT.PoppinsBold,
    fontSize: px(12),
    fontWeight: '300',
    color: ColorTheme.black,
  },
  belowContainer: { marginHorizontal: px(15), marginVertical: px(20) },
  buttonStyle: { width: px(160), backgroundColor: ColorTheme.white },
  nameTextStyle: {
    fontFamily: FONT.PoppinsBold,
    fontSize: px(12),
    fontWeight: 'bold',
    color: ColorTheme.black,
    marginLeft: px(40),
    marginTop: px(20),
  },
  descriptionTextStyle: {
    fontFamily: FONT.PoppinsRegular,
    fontSize: px(12),
    fontWeight: 'bold',
    color: ColorTheme.onboardingButton,
    marginTop: px(20),
    marginLeft: px(20),
  },
  idealText: {
    fontFamily: FONT.PoppinsRegular,
    fontSize: px(12),
    fontWeight: 'bold',
    color: ColorTheme.onboardingButton,
    marginTop: px(10),
    marginLeft: px(20),
  },
  locationText: {
    fontFamily: FONT.PoppinsRegular,
    fontSize: px(12),

    color: ColorTheme.black,
    marginTop: px(10),
    marginLeft: px(20),
  },
  amenitiesText: {
    fontFamily: FONT.PoppinsRegular,
    fontSize: px(12),
    fontWeight: 'bold',
    color: ColorTheme.onboardingButton,
    marginTop: px(10),
  },
  followersTextStyle: {
    fontFamily: FONT.PoppinsRegular,
    fontSize: px(12),
    fontWeight: 'bold',
    color: ColorTheme.black,
    marginLeft: px(40),
  },
  buttonsContainer: { flexDirection: 'row', justifyContent: 'space-evenly', marginVertical: px(5) },
  projectDetailsContainer: { flexDirection: 'row', marginVertical: px(5), paddingHorizontal: px(20) },
  touchableText: {
    color: ColorTheme.black,
    fontFamily: FONT.PoppinsRegular,

    fontSize: px(12),
    textAlign: 'center',
  },
  propertyButtonStyle: { width: deviceWidth / 1.09, marginTop: px(20) },
  buttonViewStyle: { alignItems: 'center', marginHorizontal: px(10) },
  listViewContainer: { marginVertical: px(20), backgroundColor: ColorTheme.white,justifyContent:'center' },
  selectedItemStyle: {
    fontFamily: FONT.PoppinsRegular,
    fontSize: px(11),
    fontWeight: 'bold',
    color: ColorTheme.black,
    textDecorationLine: 'underline',
    margin: px(10),
  },

  areaContainer: {
    paddingHorizontal: px(10),
    backgroundColor: ColorTheme.white,
    borderRadius: px(5),
    width: deviceWidth / 3.3,
    paddingVertical: px(10),
  },
  mapView: {
    width: deviceWidth / 1.07,
    height: deviceHeight / 3,

    alignSelf: 'center',
  },
  areaText: {
    color: ColorTheme.primaryColor,
    fontFamily: FONT.PoppinsRegular,

    fontSize: px(12),
    textAlign: 'center',
  },
  valueText: {
    color: ColorTheme.black,
    fontFamily: FONT.PoppinsRegular,
    marginTop: px(20),

    fontSize: px(12),
    textAlign: 'center',
  },
  viewText: {
    color: ColorTheme.onboardingButton,
    fontFamily: FONT.PoppinsRegular,
    marginTop: px(20),

    fontSize: px(12),
    textAlign: 'center',
  },

  underlineViewStyle: {
    backgroundColor: ColorTheme.onboardingButton,
    borderRadius: px(5),
    marginHorizontal: px(5),
    marginBottom: px(10),
    padding: px(1),
  },
  nonUnderlineViewStyle: {
    marginRight: px(5),
    marginBottom: px(5),
  },
  itemStyle: {
    fontFamily: FONT.PoppinsRegular,
    color: ColorTheme.black,
    fontSize: px(11),
    fontWeight: 'bold',
    marginVertical: px(5),
    marginHorizontal: px(10),
    padding: 5,
  },
  viewStyle: {
    paddingHorizontal: px(65),
  },
  rowView: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: px(10),

    width: deviceWidth / 1.05,
    alignSelf: 'center',
    padding: px(15),
  },
  businessCardContainer: {
    backgroundColor: ColorTheme.white,
    width: deviceWidth / 1.05,
    alignSelf: 'center',
    padding: px(15),
  },
  builderContainer: {
    flexDirection: 'row',
    width: deviceWidth / 1.05,
    alignSelf: 'center',
    margin: px(10),
    gap: px(10),
  },
  builderContainerNoDate: {
    justifyContent: 'space-evenly',
  },
  layoutView: {
    flexDirection: 'row',
    // justifyContent: 'space-around',
    paddingBottom: px(40),
    paddingHorizontal: px(20),
    // backgroundColor: 'red',
  },
  layoutViewSpaceAround: {
    justifyContent: 'space-between',
  },

  subContainer: {
    backgroundColor: ColorTheme.onboardingButton,
    padding: px(15),
    borderRadius: px(8),
  },

  headText: {
    color: ColorTheme.onboardingPrimary,
    fontFamily: FONT.PoppinsRegular,
    fontWeight: 'bold',
    fontSize: px(14),
    marginLeft: px(10),
    // textAlign: 'center',
  },
  ProjectHeighLightsContainer: {
    backgroundColor: ColorTheme.white,
    margin: px(20),
    width: deviceWidth / 1.05,
    alignSelf: 'center',
    paddingBottom: px(10),
  },
  buildingContainer: {
    width: deviceWidth / 1.05,
    height: deviceHeight / 4,
  },
  propertyImageStyle: {
    height: '100%',
    width: '100%',
  },
  propertyListStyle: {
    marginHorizontal: px(10),
    flexDirection: 'row',
  },
  propertyTextStyle: {
    paddingVertical: px(10),
    paddingHorizontal: px(5),
  },
  propertyDetailsStyle: {
    backgroundColor: ColorTheme.white,
    margin: px(10),
    borderRadius: px(5),
    shadowOffset: { width: 0, height: 2 },
    shadowColor: '#000',
    shadowOpacity: 0.2,
    // borderWidth:2,
    borderColor: 'red',
    padding: px(5),
    height: deviceHeight / 3,
    width: deviceWidth / 1.6,
  },
  imageBackgroundStyle: {
    flex: 1,
  },

  propertyCard: {
    width: '95%',
    paddingBottom: px(5),
    backgroundColor: ColorTheme.white,
    borderRadius: px(5),
    alignSelf: 'center',
    marginTop: px(15),
    flexDirection: 'column',
    justifyContent: 'space-between',
  },

  propertyCardStyle: {
    width: '95%',
    // paddingBottom: px(20),
    // backgroundColor: ColorTheme.white,
    // borderRadius: px(5),
    alignSelf: 'center',
    // marginTop: px(15),
    flexDirection: 'row',
    justifyContent: 'space-between',
  },

  propertyText: {
    color: ColorTheme.gray,
    fontFamily: FONT.PoppinsRegular,
    fontSize: px(10),
    marginHorizontal: px(5),
  },

  PropertyLabel: {
    fontFamily: FONT.PoppinsBold,
    fontSize: px(11),
    fontWeight: 'bold',
    color: ColorTheme.black,
    margin: px(5),
  },

  PropertyLabelStyle: {
    fontFamily: FONT.PoppinsBold,
    fontSize: px(11),
    fontWeight: 'bold',
    color: ColorTheme.black,
    margin: px(5),
  },
  PropertyBlue: {
    fontFamily: FONT.PoppinsBold,
    fontSize: px(11),
    fontWeight: 'bold',
    color: ColorTheme.onboardingButton,
    margin: px(5),
  },
  propertyViewStyle: {
    width: '100%',
    marginVertical: px(5),
    justifyContent: 'space-between',
    flexDirection: 'row',
    marginTop: px(130),
  },
  forSaleStyle: { backgroundColor: '#1A938C', borderRadius: px(5), justifyContent: 'center', alignItems: 'center' },
  whiteTextStyle: {
    fontFamily: FONT.PoppinsBold,
    fontSize: px(12),
    fontWeight: '500',
    color: ColorTheme.white,
    margin: px(5),
    padding: px(5),
  },
  nextImageStyle: {
    width: px(30),
    height: px(30),
    borderRadius: px(15),
    marginHorizontal: px(10),
    backgroundColor: ColorTheme.white,
  },
  viewMargin: {
    margin: px(0),
  },
  amenticeView: {
    flexDirection: 'row',
    margin: px(15),
  },

  flatPropertyStyle: {
    flexDirection: 'column',
    flex: 1,
  },
  porpertyViewStyle: { flexDirection: 'row', justifyContent: 'space-around', paddingBottom: px(40) },

  inputStyle: {
    height: px(43),
    width: deviceWidth / 1.09,
    fontSize: SIZES.small14,
    fontWeight: '400',
    color: 'black',
    marginBottom: -px(20),
  },

  arrowContainer: {
    height: 35,
    width: 35,
    borderRadius: 30,
    borderWidth: 2,
    borderColor: 'white',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    bottom: 5,
    right: 20,
    zIndex: 2,

    backgroundColor: ColorTheme.white,
    elevation: 5,
  },
  scrollContainer: {
    backgroundColor: ColorTheme.white,
    paddingVertical: px(5),
    paddingHorizontal: px(10),
    marginTop: px(10),
  },
  loaderContainer: {
    width: deviceWidth,
    height: deviceHeight,
    backgroundColor: ColorTheme.white,
    justifyContent: 'center',
    alignItems: 'center',
  },

  leadsContainer: {
    flexDirection: 'row',
    width: deviceWidth,
    justifyContent: 'space-evenly',
  },
  cinContainer: {
    flexDirection: 'row',
    width: deviceWidth / 1.05,
    justifyContent: 'space-around',
    alignSelf: 'center',
    backgroundColor: ColorTheme.white,
    paddingVertical: px(20),
    marginTop: px(10),
  },
  cinSubContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'flex-end',
  },
  cinNumContainer: {
    flex: 2,
    justifyContent: 'center',
    alignItems: 'flex-start',
    marginLeft: px(20),
  },
  leadsViewStyle: {
    borderRadius: px(15),
    elevation: px(5),
    shadowOffset: { width: 0, height: 1 },
    shadowColor: ColorTheme.black,
    shadowOpacity: 0.5,
    padding: px(20),
    backgroundColor: ColorTheme.white,
    margin: px(5),
  },
  totalLeadsTextStyle: {
    fontFamily: FONT.PoppinsMedium,
    fontWeight: '500',
    color: ColorTheme.black,
    margin: px(5),
    fontSize: px(14),
  },
  totalLeadsLabelStyle: {
    fontFamily: FONT.PoppinsMedium,
    fontWeight: '500',
    margin: px(5),
    fontSize: px(16),
    color: ColorTheme.black,
  },
  lastGradientView: {
    right: 0,
    height: 90,
  },
  cinText: {
    fontFamily: FONT.PoppinsRegular,
    fontSize: px(12),
    fontWeight: 'bold',
    color: ColorTheme.onboardingButton,
  },
  numberText: {
    fontFamily: FONT.PoppinsRegular,
    fontSize: px(12),
    fontWeight: '500',
    color: ColorTheme.black,
  },
  defaultProfile: {
    width: 100,
    height: 100,
    borderRadius: 100,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: ColorTheme.primary,
  },
  ownerText: {
    fontSize: SIZES.large,
    fontWeight: 'bold',
    color: 'white',
  },

});
