import { TextStyle, ViewStyle } from 'react-native';

export type CommonInputProps = {
  style?: ViewStyle;
  containerStyle?: ViewStyle;
  leftIcon?: React.ReactElement;
  rightIcon?: React.ReactElement;
  password?: boolean;
  placeholder?: string;
  placeholderColor?: string;
  errorvalue?: string;
  onChangeText?: (text: string) => void;
  value?: string;
  label?: string;
  onChange?: (e) => void;
  onBlur?: (e) => void;
  onFocus?: (e) => void;
  disabled?: boolean;
  keyboardType?: any;
  maxLength?: number;
  multiline?: boolean;
  numberOfLines?: number;
  labelStyle?: TextStyle;
  contentStyle?: TextStyle;
  inputRef?: any;
  outlineStyle?: ViewStyle;
  generateAIButton?: boolean;
  autogenerateDescription?: () => void;
  loader?: boolean;
};

export type CommonStyleProps = {
  textInput: TextStyle;
  label: TextStyle;
};
