import React from 'react';
import { ActivityIndicator, TouchableOpacity, View } from 'react-native';
import { TextInput } from 'react-native-paper';

import { ColorTheme, FONT, SIZES } from '@/theme';
import { deviceWidth, px } from '@/utils';

import { RNText } from '../RNText';
import { InputStyle } from './CommonInput.styles';
import { CommonInputProps } from './commonInput.types';

const CommonInput: React.FC<CommonInputProps> = ({
  style,
  password,
  errorvalue,
  placeholderColor,
  onChangeText,
  value,
  label,
  onChange,
  onBlur,
  onFocus,
  containerStyle,
  keyboardType = 'default',
  disabled,
  maxLength,
  numberOfLines,
  multiline,
  contentStyle,
  placeholder,
  inputRef,
  outlineStyle,
  generateAIButton,
  autogenerateDescription,
  loader,
}) => {
  return (
    <View style={[containerStyle]}>
      <TextInput
        mode="outlined"
        label={label}
        ref={inputRef}
        placeholderTextColor={placeholderColor || 'black'}
        placeholder={placeholder}
        secureTextEntry={password}
        onChangeText={onChangeText}
        onChange={onChange}
        onBlur={onBlur}
        autoComplete="sms-otp"
        autoCapitalize="none"
        textContentType="oneTimeCode"
        keyboardType={keyboardType ? keyboardType : 'default'}
        dense={true}
        value={value}
        disabled={disabled}
        editable={!disabled}
        maxLength={maxLength}
        numberOfLines={numberOfLines}
        multiline={multiline}
        onFocus={onFocus}
        outlineColor={errorvalue ? ColorTheme.red : ColorTheme.black}
        activeOutlineColor={errorvalue ? ColorTheme.red : '#168D86'}
        outlineStyle={[InputStyle.outline, outlineStyle]}
        style={[InputStyle.style, style]}
        contentStyle={[InputStyle.content, contentStyle]}
        textColor="black"
      />

      {generateAIButton && (
        <TouchableOpacity
          onPress={autogenerateDescription}
          style={{
            position: 'absolute',
            top: px(130),
            paddingRight: px(30),
            alignSelf: 'flex-end',
          }}>
          {loader ? (
            <ActivityIndicator />
          ) : (
            <RNText
              style={{
                color: '#1A938C',
                fontSize: SIZES.small,
                fontWeight: '600',
              }}>
              Generate with AI
            </RNText>
          )}
        </TouchableOpacity>
      )}
    </View>
  );
};

export default CommonInput;
