import { Platform, StyleSheet } from 'react-native';

import { ColorTheme, FONT, SIZES } from '@/theme';
import { deviceWidth, px } from '@/utils';

export const styles = StyleSheet.create({
  flexView: {
    flex: 1,
  },
  rowView: {
    paddingLeft: px(20),
    height: px(100),
  },
  nearuText: {
    fontFamily: FONT.PoppinsRegular,
    fontSize: px(14),
    fontWeight: '700',
    color: ColorTheme.white,
    width: 'auto',
    marginTop: px(45),
    marginLeft: px(22),
  },
  locationText: {
    fontFamily: FONT.PoppinsRegular,
    fontSize: px(12),

    color: ColorTheme.white,
    width: 'auto',
  },
  areaText: {
    fontFamily: FONT.PoppinsRegular,
    // width: 200,
    fontSize: SIZES.small11,
    fontWeight: '600',
    color: 'black',
    width: 'auto',
  },
  lineView: {
    borderBottomWidth: StyleSheet.hairlineWidth,
    width: deviceWidth / 1.3,
    alignSelf: 'center',
    // marginTop: 20,
    borderColor: ColorTheme.nearLukGray,
  },
  nearlukView: {
    width: deviceWidth,
    padding: 20,
    gap: 15,
    // marginTop: 10,
    paddingHorizontal: 20,
  },
  nearlukText: {
    fontFamily: FONT.PoppinsBold,
    fontSize: SIZES.medium18,
    fontWeight: '600',
    lineHeight: 26,
    color: 'black',
  },
  gradientView: {
    left: -20,
    right: 0,
    height: 105,
    width: deviceWidth,
  },
  subGradientView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: deviceWidth,
    alignSelf: 'center',
    paddingTop: 5,
    // borderWidth: 1,
  },
  belowGradientView: {
    flexDirection: 'row',
    width: deviceWidth / 1.09,
    alignSelf: 'center',
    // marginTop: 10,
  },
  lastGradientView: {
    right: 0,
    height: 90,
  },
  subNearlukText: {
    fontFamily: FONT.PoppinsRegular,
    fontSize: SIZES.xSmall,
    fontWeight: '400',
    lineHeight: 14,
    color: 'black',
  },
  storyImage: {
    width: px(130),
    height: px(180),
    borderRadius: 10,
  },
  listContainer: {
    width: deviceWidth,
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 20,
  },
  emptyContainer: {
    width: deviceWidth,
    alignItems: 'center',
    height: 100,
    justifyContent: 'center',
  },

  navButton: {
    backgroundColor: '#DEEBF3',
    padding: 10,
    borderRadius: 100,
    borderColor: '#92C8EA',
    borderWidth: StyleSheet.hairlineWidth,
  },
  navRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 15,
    marginRight: px(10),
    marginTop: px(30),
  },
  navChild: {
    justifyContent: 'space-between',
    display: 'flex',
    flexDirection: 'row',
    marginTop: Platform.OS === 'android' ? 10 : 0,
    alignItems: 'center',
    marginHorizontal: 20,
    // marginBottom: 10,
    backgroundColor: 'white',
  },
  stories: {
    borderBottomColor: '#E4E4E4',
    borderTopColor: '#E4E4E4',
    borderBottomWidth: 6,
    width: deviceWidth,
    paddingHorizontal: 10,
    padding: 10,
  },
  storyCard: {
    alignSelf: 'center',
    backgroundColor: ColorTheme.primaryColor,
    borderRadius: 100,
    borderWidth: 1,
    padding: 5,
    marginTop: 5,
    borderColor: 'white',
    position: 'absolute',
    bottom: px(10),
  },
  countStyle: {
    position: 'absolute',
    zIndex: 2,
    top: 0,
    right: -5,
    width: px(20),
    height: px(20),
    borderRadius: px(10),
    backgroundColor: ColorTheme.primary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  countText: {
    fontSize: SIZES.small14,
    color: ColorTheme.white,
    fontWeight: '500',
  },
  defaultView: {
    width: px(130),
    height: px(180),
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: ColorTheme.primary,
  },
  defaultText: {
    fontSize: SIZES.xxxLarge,
    fontWeight: 'bold',
    color: ColorTheme.white,
  },
  modelViewStyle: {
    // backgroundColor:'red',
    height: deviceWidth,
    width: deviceWidth,
    flex: 1,
    padding: 20,
    marginTop:px(30)
  },
  main: {
    backgroundColor: 'white',
    shadowOffset: {
      width: 1,
      height: 1,
    },
    shadowOpacity: Platform.OS === 'android' ? 1 : 0.3,
    shadowRadius: 3,
    shadowColor: 'gray',
    elevation: 10,
    height: '14%',
  },
  container: {
    height: '100%',
    flexDirection: 'row',
  },
  labelStyle: {
    fontSize: SIZES.xLarge,
    fontFamily: FONT.PoppinsMedium,
    textTransform: 'capitalize',
    color: 'black',
    fontWeight: '500',
    marginLeft: 20,
  },
  subLabel: {
    fontFamily: FONT.PoppinsRegular,
    fontSize: 12,
    marginLeft: 20,
    marginTop: 5,
    color: 'black',
  },
});
