export const loginConstants = {
  noAccount: 'Do not have account? ',
  gotoSignUp: 'SignUp',
  loginWith: 'or login with',
};
export const signUpConstants = {
  account: 'Create Account',
  accAlready: 'Already have an Account? ',
  login: 'Log in',
};
export const otpConstants = {
  otpDigit: 'Enter OTP sent to',
  noOtp: 'Did not receive OTP code ? ',
  reSend: 'Resend OTP',
};

export const userData = {
  __v: 0,
  _id: '65def3304406b803aeeb165b',
  address_lane1: null,
  address_lane2: null,
  adhaar: null,
  averageRating: null,
  bio: null,
  city: 'Indore',
  country: null,
  cover_pic: null,
  createdAt: '2024-02-28T08:47:44.365Z',
  dob: null,
  emailOtp: null,
  emailOtpBase32Key: null,
  fname: 'harshit ',
  following: null,
  gallery: { _id: '65def3304406b803aeeb165a', cover_pic: [], profile_pic: [], story: [[Object], [Object], [Object]] },
  gender: null,
  isSubscribed: false,
  isVerified: true,
  isVerifiedEmail: false,
  last_login: '2024-03-29T06:40:26.325Z',
  leads_available: 5,
  lname: 'Choudhary ',
  location: null,
  mobile_no: '9644933661',
  otp: '270688',
  otp_valid: '2024-03-29T06:49:54.818Z',
  pan: null,
  password: null,
  pincode: null,
  profile_pic: null,
  remainder_email_count: 0,
  role: 'USER',
  seller_id: 'NRLK2024050',
  social_media: [],
  state: null,
  updatedAt: '2024-03-29T06:40:26.325Z',
  website: null,
};
