export const drawerContentData = [
  {
    label: 'Recently Viewed',
    img: require('@/assets/images/customImage/recent.png'),
    // link: 'ResidentialProperties',
    type: 'creditluk',
  },
  {
    label: 'Investment Sharing',
    img: require('@/assets/images/customImage/investment.png'),
    type: 'creditluk',
  },
  {
    label: 'Auctions',
    img: require('@/assets/images/customImage/auction2.png'),
    type: 'creditluk',
  },
  {
    label: 'CreditLuk',
    img: require('@/assets/images/customImage/creditluk.png'),
    type: 'creditluk',
  },
  {
    label: 'Coliving',
    img: require('@/assets/images/customImage/friend1.png'),
    type: 'Coliving',
    propertyType: [
      'Flat',
      'Studio Apartment',
      'Apartment',
      'Villa',
      'Independent House',
      'PG',
      'Coliving space',
      'Hostel',
    ],
  },
  {
    label: 'Rent Pay',
    img: require('@/assets/images/customImage/rent.png'),
    type: 'creditluk',
  },
  {
    label: 'Hostel',
    img: require('@/assets/images/customImage/hostel1.png'),
    type: 'Hostel',
    propertyType: ['Hostel'],
  },
  {
    label: 'Sharing Properties',
    img: require('@/assets/images/customImage/shareproperty.png'),
    type: 'creditluk',
  },
  {
    label: 'Office Spaces',
    img: require('@/assets/images/customImage/building1.png'),
    type: 'Office space',
    propertyType: ['Office spaces'],
  },
  {
    label: 'Event Spaces',
    img: require('@/assets/images/customImage/eventspace.png'),
    type: 'creditluk',
  },
  {
    label: 'Parking Spaces',
    img: require('@/assets/images/customImage/parking.png'),
    type: 'creditluk',
  },
  {
    label: 'Commercial Properties',
    img: require('@/assets/images/customImage/commercial.png'),
    type: 'Commercial',
    propertyType: [
      'Hotels',
      'Resorts',
      'Retail',
      'Showroom',
      'Shopping mall',
      'Educational',
      'Office spaces',
      'Industrial',
      'Land/plot',
    ],
  },
  {
    label: 'Properties for Sale',
    img: require('@/assets/images/customImage/saleproperty.png'),
    type: 'Properties for Sale',
    propertyFor: 'Buy',
  },
  {
    label: 'Properties for Rent',
    img: require('@/assets/images/customImage/rentproperty.png'),
    type: 'Properties for Rent',
    propertyFor: 'Rent',
  },
  {
    label: 'Land/Plot',
    img: require('@/assets/images/customImage/rail1.png'),
    type: 'Land or Plot',
    propertyType: ['Residential', 'Agricultural', 'Industrial', 'Institutional'],
  },
];
