import { StyleSheet } from 'react-native';

import { ColorTheme, FONT, SIZES } from '@/theme';
import { deviceWidth, px } from '@/utils';

export const styles = StyleSheet.create({
  btnStyle: {
    marginBottom: 10,
    width: 160,
    borderRadius: 30,
    // marginRight: 20,
    minHeight: 40,
    shadowColor: 'black',
    shadowOffset: {
      height: 1,
      width: 1,
    },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 5,
  },
  btnStyle1: {
    marginBottom: 10,
    width: 160,
    borderRadius: 30,
    // marginRight: 20,
    minHeight: 40,
    backgroundColor: 'white',
    shadowColor: 'black',
    shadowOffset: {
      height: 1,
      width: 1,
    },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 5,
  },
  btnText: {
    color: 'black',
    lineHeight: 21,
    fontWeight: '400',
    fontSize: SIZES.medium15,
  },
  btnContainer: {
    height: 80,
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    width: deviceWidth / 1.09,
  },

  container: {
    width: deviceWidth,
    alignItems: 'center',
    // height: px(200),
    marginTop: px(5),
    // backgroundColor: 'red',
  },
  cardContainer: {
    backgroundColor: 'white',
    width: deviceWidth / 1.09,
    height: 125,
    padding: 13,
    borderRadius: 10,
    shadowColor: 'black',
    shadowOffset: {
      height: 1,
      width: 1,
    },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 10,
    marginTop: 10,
    // justifyContent: "center",
  },
  cardView: { flex: 1 },
  cardHeader: {
    flex: 10,
    flexDirection: 'row',
  },
  cardHeadLeft: {
    flex: 7,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    height: 40,
  },
  imgStyle: { width: px(35), height: px(35), borderRadius: px(35), flex: 1 },
  nameView: { paddingLeft: 10, justifyContent: 'center', flex: 5 },
  nameText: {
    fontSize: SIZES.small,
    fontWeight: '500',
    color: '#378E6C',
  },
  defaultprofile: {
    width: px(35),
    height: px(35),
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: ColorTheme.primary,
  },
  defaultText: {
    fontSize: SIZES.medium15,
    fontWeight: 'bold',
    color: 'white',
  },
  contacted: {
    fontSize: px(10),
    fontWeight: '400',
    color: 'rgba(0,0,0,0.5)',
  },
  cardHeadRight: { flex: 2, height: 40, justifyContent: 'center' },
  actionView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  actionText: {
    fontSize: px(9),
    fontWeight: '400',
    color: 'rgba(0,0,0,0.5)',
  },
  favBtn: { paddingLeft: 5 },
  cardContent: {
    flex: 10,
    flexDirection: 'row',
  },
  contentView: {
    flex: 7,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    height: 40,
  },
  contentTop: {
    paddingLeft: 10,
    justifyContent: 'center',
    flex: 5,
    marginTop: 10,
  },
  propName: { fontSize: SIZES.small, fontWeight: '600', color: 'black' },
  propAdd: {
    fontSize: px(10),
    fontWeight: '400',
    fontFamily: FONT.PoppinsRegular,
    color: 'black',
    opacity: 0.5,
    lineHeight: SIZES.medium15,
  },
  priceContainer: { flex: 2, height: 40, justifyContent: 'flex-start' },
  priceView: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'flex-start',
    marginTop: 10,
  },
  priceText: {
    fontSize: SIZES.small,
    fontFamily: FONT.PoppinsMedium,
    color: 'black',
    fontWeight: '600',
  },
  modalView: {
    marginTop: px(50),
  },
  modalcontentView: {
    width: deviceWidth / 1.09,
    flexDirection: 'column',
    // alignItems: 'flex-start',
    padding: px(20),
    // flexDirection: 'row',
    alignItems: 'flex-start',
    // justifyContent: 'flex-start',
  },
  roleText: {
    fontSize: SIZES.small,
    // fontWeight: '400',
    color: ColorTheme.black,
  },
  userText: {
    fontSize: SIZES.large,
    fontWeight: '600',
    color: ColorTheme.black,
  },
  mobText: {
    fontSize: SIZES.large,
    fontWeight: '600',
    color: ColorTheme.primary,
    textDecorationLine: 'underline',
  },
});
