import { StyleSheet } from 'react-native';

import { ColorTheme, FONT, SIZES } from '@/theme';
import { deviceHeight, deviceWidth, px } from '@/utils';

export const styles = StyleSheet.create({
  mainContainer: {
    flex: 1,
   
  },
  stepContainer: {
    alignContent: 'center',
    marginTop: px(70),
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: px(20),
  },
  stepHeader: {
    alignContent: 'center',
    marginTop: px(20),
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerText1: {
    fontSize: SIZES.medium18,
    fontWeight: '500',
    lineHeight: SIZES.xLarge,
    color: ColorTheme.black,
  },
  headerText2: {
    fontSize: SIZES.small14,
    fontWeight: '500',
    lineHeight: SIZES.xLarge,
    color: '#666666',
  },
  freeText: {
    color: '#1A938C',
    fontSize: SIZES.small14,
    fontWeight: '500',
    lineHeight: SIZES.xLarge,
  },
  stepText: {
    color: ColorTheme.onboardingPrimary,
    fontFamily: FONT.PoppinsMedium,
    fontWeight: 'bold',
    fontSize: px(20),
    textAlign: 'center',
  },

  SingleBtnStyle: {
    fontSize: px(14),
    fontFamily: FONT.PoppinsThin,
    fontWeight: '500',
    color: ColorTheme.black,
  },
  inputStyle: {
    height: px(43),
    width: deviceWidth / 1.09,
    fontSize: SIZES.small14,
    fontWeight: '400',
    color: 'black',
    borderColor: ColorTheme.gray,
    backgroundColor: ColorTheme.white,
    alignSelf: 'center',
    marginTop: px(20),
  },
  smallInputStyle: {
    height: px(43),
    width: deviceWidth / 2.3,
    fontSize: SIZES.small14,
    fontWeight: '400',
    color: 'black',
  },
  inputView: { width: deviceWidth },
  buttonContainer: {
    width: px(150),
    borderRadius: 5,
    backgroundColor: ColorTheme.white,
    borderWidth: 0.5,
    borderColor: ColorTheme.onboardingButton,
    elevation: 5,
  },
  BtnStyle: {
    fontSize: px(12),
    fontFamily: FONT.PoppinsThin,
    fontWeight: '500',
    color: ColorTheme.onboardingPrimary,
  },
  nextContainer: {
    width: px(150),
    borderRadius: 5,
    backgroundColor: ColorTheme.onboardingButton,

    elevation: 5,
  },
  nextStyle: {
    fontSize: px(12),
    fontFamily: FONT.PoppinsThin,
    fontWeight: '500',
    color: ColorTheme.black,
  },
  bottomBtnsStyle: {
    alignSelf: 'center',
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    width: deviceWidth,
    bottom: px(50),
    position: 'absolute',
  },
  wrapper: {
    marginTop: px(30),
    // height: px(150),
  },
  toggleActiveBtn: {
    backgroundColor: ColorTheme.white,
    borderRadius: px(6),
    borderWidth: 0,
    height: px(26),
  },
  toggleActiveText: {
    color: ColorTheme.black,
    fontSize: SIZES.small,
    fontWeight: '600',
    lineHeight: SIZES.xLarge,
  },
  toggleInActiveText: {
    color: ColorTheme.white,
    fontSize: SIZES.small,
    fontWeight: '600',
    lineHeight: SIZES.xLarge,
  },
  toggleInActiveBtn: { borderRadius: px(6), borderWidth: 0, height: px(26) },
  toggleStyle: { backgroundColor: ColorTheme.onboardingPrimary },
  toggleView: { backgroundColor: ColorTheme.onboardingPrimary, padding: px(10), borderRadius: px(12) },
  modalBackground: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContainer: {
    backgroundColor: '#fff',
    borderRadius: 10,
    padding: 20,
    width: '80%',
    maxHeight: '60%',
  },

  selectedText: {
    backgroundColor: ColorTheme.onboardingPrimary,
    borderRadius: 5,
    paddingHorizontal: 10,
    color: ColorTheme.white,
  },
  selectedCitiesContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 10,
    width: '90%',
    alignSelf: 'center',
  },
  selectedCityButton: {
    backgroundColor: ColorTheme.onboardingPrimary,
    borderRadius: 5,
    paddingVertical: 10,
    paddingHorizontal: 10,
    marginRight: 10,
    marginBottom: 10,
  },
  selectedCityText: {
    backgroundColor: ColorTheme.onboardingPrimary,
    borderRadius: 5,
    paddingHorizontal: 10,
    color: ColorTheme.white,
  },
  renderText: {
    fontSize: px(14),
    fontFamily: FONT.PoppinsThin,
    fontWeight: '500',
    color: ColorTheme.black,
    marginTop: px(10),
    paddingVertical: px(5),
  },
  addBtn: {
    width: px(60),
    height: px(30),
    backgroundColor: '#F5F9F9',
    justifyContent: 'space-around',
    alignItems: 'center',
    flexDirection: 'row',
    padding: px(5),
  },
  addView: {
    width: deviceWidth / 1.09,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  errorText: { color: ColorTheme.danger, fontSize: SIZES.small, textAlign: 'left', marginLeft: px(20) },
  errorTransaction: { color: ColorTheme.danger, fontSize: SIZES.small, textAlign: 'left' },
  agentCheck: {
    width: '45%',
    height: px(50),
    borderWidth: 1,
    borderRadius: px(10),
    flexDirection: 'row',
    borderColor: ColorTheme.gray,
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: px(15),
  },
  agentText: { fontSize: SIZES.medium15, color: ColorTheme.black },
  errorDeal: {
    width: deviceWidth / 1.09,
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  dealView: {
    width: deviceWidth / 1.09,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: px(10),
  },
  emptyContainer: {
    width: deviceWidth / 1.09,
    alignSelf: 'center',
    minHeight: deviceHeight / 2.5,
  },
});
