import { StyleSheet } from 'react-native';

import { ColorTheme, FONT, SIZES } from '@/theme';
import { deviceHeight, deviceWidth, px } from '@/utils';

export const styles = StyleSheet.create({
  modalContainer: {
    // flex: 1,
    backgroundColor: '#fff',
    width: deviceWidth,
    shadowColor: 'gray',
    // padding: 5,
    borderRadius: 5,
  },
  BtnTextStyle: {
    fontFamily: FONT.PoppinsMedium,
    fontSize: SIZES.small14,
    lineHeight: SIZES.large,
    fontWeight: '600',
    color: 'black',
  },
  BtnStyle: {
    backgroundColor: ColorTheme.onboardingButton,
    minHeight: px(45),
    marginTop: px(10),
  },
  headText: {
    fontFamily: FONT.PoppinsMedium,
    fontSize: SIZES.small14,
    lineHeight: SIZES.large,
    fontWeight: 'bold',
    color: 'black',
    marginBottom: px(10),
  },
  planText: {
    fontFamily: FONT.PoppinsMedium,
    fontSize: SIZES.small14,
    lineHeight: SIZES.large,
    fontWeight: '600',
    color: 'black',
  },
  detailText: {
    fontFamily: FONT.PoppinsMedium,
    fontSize: SIZES.small14,
    lineHeight: SIZES.large,
    fontWeight: 'bold',
    color: 'black',
    marginTop: px(20),
    marginLeft: px(10),
  },
  subTitle: {
    fontSize: SIZES.small,
    lineHeight: SIZES.medium18,
    fontWeight: '300',
    fontFamily: FONT.PoppinsMedium,
    color: 'black',
    marginTop: px(10),
  },
  cardView: {
    width: deviceWidth / 1.09,
    elevation: 5,
    backgroundColor: ColorTheme.nearLukGray4,
    borderRadius: px(10),
    marginTop: px(10),
    paddingVertical: px(20),
    paddingHorizontal: px(15),
  },
  activeCard: {
    width: deviceWidth / 1.09,
    elevation: 5,
    backgroundColor: ColorTheme.nearLukGray6,
    borderRadius: px(10),
    marginTop: px(10),
    marginBottom: px(20),
    padding: px(20),
  },
  tickMark: {
    width: SIZES.medium18,
    height: SIZES.medium18,
  },
  activeText: {
    color: 'green',
    lineHeight: SIZES.medium18,
    fontSize: SIZES.small,
    fontFamily: FONT.PoppinsMedium,
    fontWeight: '600',
    paddingLeft: px(5),
  },
  activeBtn: {
    backgroundColor: '#C4FAC6',
    height: px(30),
    width: px(120),
    borderRadius: px(30),
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: px(10),
  },
  deactiveBtn: {
    backgroundColor: ColorTheme.onboardingPrimary,
    height: px(30),
    width: px(120),
    borderRadius: px(30),
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: px(10),
  },
  flexRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    height: px(50),
    width: deviceWidth / 1.25,
  },
  singleDetail: {
    height: px(50),
    justifyContent: 'space-around',
    alignItems: 'flex-start',
    margin: 10,
  },
  textThin: {
    fontSize: SIZES.small,
    fontWeight: '400',
    fontFamily: FONT.PoppinsThin,
    color: '#7E7E7E',
  },
  textThick: {
    fontSize: SIZES.small,
    fontWeight: '600',
    fontFamily: FONT.PoppinsThin,
    color: 'black',
  },
  planRow: {
    flexDirection: 'row',
    width: deviceWidth / 1.09,
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 10,
    marginBottom: 20,
    marginTop: 10,
  },
});
